{
 "title": "Redis Monitoring",
 "description": "Dashboard for Redis servers",
 "time": { "from": "now-5m", "to": "now-1m" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   { "name": "db", "label": "Database", "query": "redis" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_avg_latency, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(count by (server)(count_over_time(redis_avg_latency{namespace=\"$namespace\"}[$__range])))"
    }
   },
   {
    "name": "inter",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "db_name",
    "query": {
     "query": "query_result(count by (server)(count_over_time(redis_avg_latency{namespace=~\"$namespace\", server=~\"$instance\"}[$__range])))"
    }
   },
   {
    "name": "pod_name",
    "label": "pod_name",
    "query": {
     "query": "query_result(count by (exported_pod)(kube_pod_container_info{exported_namespace=\"$namespace\", exported_container=~\"$db_name\"}))"
    }
   },
   {
    "name": "pod_name_history",
    "label": "pod_name_history",
    "query": {
     "query": "query_result(count by (exported_pod)(count_over_time(kube_pod_container_info{exported_namespace=\"$namespace\", exported_container=~\"$db_name\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of replicas",
   "type": "stat",
   "description": "Number of redis data replicas",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count by (server)(count_over_time(redis_avg_latency{namespace=\"$namespace\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Redis Versions",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "avg by (deployment, label_app_kubernetes_io_version) (kube_deployment_labels{namespace=\"$namespace\", label_redis_dbaas_adapter=\"redis-dbaas-adapter\"})",
     "legendFormat": "123"
    }
   ]
  },
  {
   "title": "CPU usage: $instance",
   "type": "stat",
   "description": "Shows CPU usage selected redis instance",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Millicores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container=~\"$db_name\",namespace=\"$namespace\"}[$inter])) * 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "CPU Usage",
     "measurement": "/^$db$/",
     "query": "SELECT last(\"value\") FROM \"cpu/usage_rate\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" = '$namespace' AND \"container_name\" = '$container_name' AND time > now() - 150s",
     "select": [
      [
       { "params": [ "used_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$namespace$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage: $instance",
   "type": "stat",
   "description": "Shows the RAM usage of the selected redis instance",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"$db_name\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Redis instance status: $instance",
   "type": "state-timeline",
   "description": "Shows the status of redis pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$instance",
     "crit": -1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "min(label_replace(sum(((kube_pod_status_phase{exported_namespace=\"$namespace\", exported_pod=~\"$pod_name_history\", phase=\"Failed\"} * 12) or \n(kube_pod_status_phase{exported_namespace=\"$namespace\", exported_pod=~\"$pod_name_history\", phase=\"Pending\"} * 4) or\n(kube_pod_status_phase{exported_namespace=\"$namespace\", exported_pod=~\"$pod_name_history\", phase=\"Running\"} * 1) or (kube_pod_status_ready{exported_namespace=\"$namespace\", exported_pod=~\"$pod_name_history\", condition=\"false\"} * 2) or \n(kube_pod_status_phase{exported_namespace=\"$namespace\", exported_pod=~\"$pod_name_history\", phase=\"Succeeded\"} * 8) or \n(kube_pod_status_phase{exported_namespace=\"$namespace\", exported_pod=~\"$pod_name_history\", phase=\"Unknown\"} * 16))) by (exported_pod), \"redis_depl\", \"$1\", \"exported_pod\", \"($db_name).*\")) by (redis_depl)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{redis_depl}}",
     "query": "SELECT last(\"value\")/last(\"value\") as \"value\"  FROM \"uptime\" WHERE $timeFilter and \"namespace_name\"='$namespace' and container_name != 'dbaas-redis-adapter' and container_name != 'redis-monitoring-agent' and  container_name != '' and  container_name != 'deployment'  group by time($__interval*3), container_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "short",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency: $instance",
   "type": "timeseries",
   "description": "Shows the latency (response time) of the selected redis instance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Latency, ms",
     "expr": "sum(redis_avg_latency{namespace=\"$namespace\", server=~\"$instance\"} >= 0) by (server)",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{server}}",
     "measurement": "/^$db$/",
     "query": "SELECT mean(\"avg_latency\") FROM /^$db$/ WHERE (\"host\" =~ /^$namespace$/ AND \"server\" =~ /^$instance$/)  and avg_latency >=0 AND $timeFilter GROUP BY time($inter) fill(null)",
     "select": [
      [
       { "params": [ "avg_latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$namespace$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Clients: $instance",
   "type": "timeseries",
   "description": "Shows the number of clients connected to the selected redis instance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(redis_clients{server=~\"$instance\"}) by (server)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "{{server}}",
     "measurement": "/^$db$/",
     "query": "SELECT last(\"clients\") FROM /^$db$/ WHERE (\"host\" =~ /^$namespace$/ AND \"server\" =~ /^$instance$/) AND time > now() - 150s",
     "select": [
      [
       { "params": [ "clients" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$namespace$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "DB Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Command Calls: $instance",
     "type": "timeseries",
     "description": "Total number of commands processed by the redis instance over 1m interval",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Command calls per metric interval",
       "expr": "avg(round(topk(5, irate(redis_total_commands_processed{server=~\"$instance\"} [1m])))) by (server)",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{server}}",
       "measurement": "/^$db$/",
       "select": [
        [
         { "params": [ "total_commands_processed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Commands Executed per second: $instance",
     "type": "timeseries",
     "description": "Shows the number of operations per second for the selected redis instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(redis_instantaneous_ops_per_sec{server=~\"$instance\"}) by (server)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{server}}",
       "measurement": "/^$db$/",
       "query": "SELECT mean(\"instantaneous_ops_per_sec\") FROM /^$db$/ WHERE (\"host\" =~ /^$namespace$/ AND \"server\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "instantaneous_ops_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Items per DB: $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(redis_keyspace_keys{server=~\"$instance\"}) by (database, server)",
       "legendFormat": "{{ database}}: {{ server}}"
      }
     ]
    },
    {
     "title": "Hits / Misses rate: $instance",
     "type": "timeseries",
     "description": "The hit rate is the number of cache hits divided by the total number of memory requests over a given time interval.\n\nThe miss rate is similar in form: the total cache misses divided by the total number of memory requests expressed as a percentage over a time interval.\n\nIf the cache hit ratio is lower than ~0.8 then a significant amount of the requested keys are evicted, expired, or do not exist at all. It is crucial to watch this metric while using Redis as a cache. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(redis_keyspace_hitrate{server=~\"$instance\"}) by (server)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "__auto",
       "measurement": "/^$db$/",
       "select": [
        [
         { "params": [ "keyspace_hitrate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Expired/Evicted Keys: $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(redis_expired_keys{server=~\"$instance\"}[$inter])) by (server)",
       "legendFormat": "Expired: {{ server}}"
      },
      {
       "expr": "sum(rate(redis_evicted_keys{server=~\"$instance\"}[$inter])) by (server)",
       "legendFormat": "Evicted: {{ server}}"
      }
     ]
    },
    {
     "title": "Expiring vs Not-Expiring Keys: $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(redis_keyspace_keys{server=~\"$instance\"}) by (server) - sum (redis_keyspace_expires{server=~\"$instance\"}) by (server)",
       "legendFormat": "Not expiring: {{ server }}"
      },
      {
       "expr": "sum(redis_keyspace_expires{server=~\"$instance\"}) by (server)",
       "legendFormat": "Expiring: {{ server}}"
      }
     ]
    },
    {
     "title": "CRUD operations: $instance",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(redis_set_op{namespace=\"$namespace\", server=~\"$instance\"}) by (server)",
       "legendFormat": "SET: {{server}}"
      },
      {
       "expr": "sum(redis_get_op{namespace=\"$namespace\", server=~\"$instance\"}) by (server)",
       "legendFormat": "GET: {{server}}"
      },
      {
       "expr": "sum(redis_del_op{namespace=\"$namespace\", server=~\"$instance\"}) by (server)",
       "legendFormat": "DEL: {{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU/RAM Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory usage over time: $instance",
     "type": "timeseries",
     "description": "Summary of Memory usage by container $instance.\n\nThe red line shows available memory volume for the container.\n\nThe orange line shows requested memory for the container.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "usage: $tag_pod_name",
       "expr": "sum(container_memory_working_set_bytes{container=~\"$db_name\",namespace=\"$namespace\"}) by (pod)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Usage: {{pod}}",
       "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" = '$namespace' AND \"container_name\" = '$container_name' AND $timeFilter GROUP BY time($inter), pod_name fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "request: $tag_pod_name",
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container=~\"$db_name\",exported_namespace=\"$namespace\"}) by (exported_pod)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Request: {{exported_pod}}",
       "query": "SELECT mean(\"value\") FROM \"memory/request\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" = '$namespace' AND \"container_name\" = '$container_name' AND $timeFilter GROUP BY time($inter), pod_name fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU usage over time: $instance",
     "type": "timeseries",
     "description": "Summary of CPU usage by process $instance.\n\nThe red line shows limit of CPUs usage for the process.\n\nThe values is indicated in Millicores. It is a special Kubernates metric means CPU core split into 1000 units.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "usage: $tag_pod_name",
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container=~\"$db_name\",namespace=\"$namespace\"}[$inter])) by (pod)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Usage: {{pod}}",
       "query": "SELECT mean(value) FROM \"cpu/usage_rate\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" = '$namespace' AND \"container_name\" = '$container_name' AND $timeFilter GROUP BY time($inter), pod_name fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "limit: $tag_pod_name",
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{container=~\"$db_name\",exported_namespace=\"$namespace\"}) by(exported_pod)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Limits: {{exported_pod}}",
       "query": "SELECT mean(value) FROM \"cpu/limit\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" = '$namespace' AND \"container_name\" = '$container_name' AND $timeFilter GROUP BY time($inter), pod_name fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "request: $tag_pod_name",
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container=~\"$db_name\",exported_namespace=\"$namespace\"}) by(exported_pod)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Requests: {{exported_pod}}",
       "query": "SELECT mean(value) FROM \"cpu/request\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" = '$namespace' AND \"container_name\" = '$container_name' AND $timeFilter GROUP BY time($inter), pod_name fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Redis Memory Usage: $instance",
     "type": "timeseries",
     "description": "Shows the RAM + mapped memory usage of the selected redis instance\nMax is the maxmemory limit in config",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "Used",
       "expr": "avg(redis_used_memory{server=~\"$instance\"}) by (server)",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Used: {{server}}",
       "measurement": "/^$db$/",
       "query": "SELECT mean(\"used_memory\") FROM /^$db$/ WHERE (\"host\" =~ /^$namespace$/ AND \"server\" =~ /^$instance$/) AND $timeFilter GROUP BY time($inter) fill(null)",
       "select": [
        [
         { "params": [ "used_memory" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "Peak",
       "expr": "avg(redis_maxmemory{server=~\"$instance\"}) by (server)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "Max: {{server}}",
       "measurement": "/^$db$/",
       "select": [
        [
         { "params": [ "used_memory_peak" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Receive/Transmit Bandwidth: $instance",
     "type": "timeseries",
     "description": "Shows network traffic in bytes per second for the pod",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod_name\"}[$inter])) by (pod)",
       "legendFormat": "RX: {{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod_name\"}[$inter])) by (pod)",
       "legendFormat": "TX: {{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted Packets: $instance",
     "type": "timeseries",
     "description": "Shows network packets for pod",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=~\"$namespace\", pod=~\"$pod_name\"}[$inter])) by (pod)",
       "legendFormat": "RX: {{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{namespace=~\"$namespace\", pod=~\"$pod_name\"}[$inter])) by (pod)    ",
       "legendFormat": "TX: {{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted Packets Dropped: $instance",
     "type": "timeseries",
     "description": "Shows dropped packets for pod",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\", pod=~\"$pod_name\"}[$inter])) by (pod)",
       "legendFormat": "RX: {{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\", pod=~\"$pod_name\"}[$inter])) by (pod)",
       "legendFormat": "TX: {{pod}}"
      }
     ]
    },
    {
     "title": "Redis Network I/O: $instance",
     "type": "timeseries",
     "description": "Shows the network input and output usage of selected redis instance.\nGreen bars show the tx_rate for the container, meaning download volumes.\nYellow bars shows the rx_rate for the container, meaning upload volumes.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "alias": "Input",
       "expr": "sum(rate(redis_instantaneous_input_kbps{server=~\"$instance\"} [$inter])) by (server)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "Input: {{server}}",
       "measurement": "/^$db$/",
       "select": [
        [
         { "params": [ "instantaneous_input_kbps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "Output",
       "expr": "sum(rate(redis_instantaneous_output_kbps{server=~\"$instance\"} [$inter])) by (server)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "Output: {{server}}",
       "measurement": "/^$db$/",
       "select": [
        [
         { "params": [ "instantaneous_output_kbps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}