// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	time "time"

	redis "github.com/Netcracker/qubership-redis/redis-operator/dbaas/pkg/redis"
	mock "github.com/stretchr/testify/mock"
)

// RedisClientInterface is an autogenerated mock type for the RedisClientInterface type
type RedisClientInterface struct {
	mock.Mock
}

// Addr provides a mock function with given fields:
func (_m *RedisClientInterface) Addr() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *RedisClientInterface) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: key
func (_m *RedisClientInterface) Get(key string) (string, error) {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitRedisClient provides a mock function with given fields: address, password, caPath, database, tlsEnabled
func (_m *RedisClientInterface) InitRedisClient(address string, password string, caPath string, database int, tlsEnabled bool) redis.RedisClientInterface {
	ret := _m.Called(address, password, caPath, database, tlsEnabled)

	var r0 redis.RedisClientInterface
	if rf, ok := ret.Get(0).(func(string, string, string, int, bool) redis.RedisClientInterface); ok {
		r0 = rf(address, password, caPath, database, tlsEnabled)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.RedisClientInterface)
		}
	}

	return r0
}

// Ping provides a mock function with given fields:
func (_m *RedisClientInterface) Ping() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, value, expiration
func (_m *RedisClientInterface) Set(key string, value string, expiration time.Duration) error {
	ret := _m.Called(key, value, expiration)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, time.Duration) error); ok {
		r0 = rf(key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRedisClientInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewRedisClientInterface creates a new instance of RedisClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRedisClientInterface(t mockConstructorTestingTNewRedisClientInterface) *RedisClientInterface {
	mock := &RedisClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
