{{- if and .Values.dbaas.createIngress (include "fromValuesThenEnvElseDefault" (dict "dotVar" .Values.dbaas.install "envVar" .Values.DBAAS_ENABLED "default" true )) .Values.CLOUD_PUBLIC_HOST }}
{{- if and (.Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1") (eq (.Values.PAAS_PLATFORM | default "KUBERNETES") "KUBERNETES") }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    {{- include "redis.defaultLabels" . | nindent 4 }}
  name: {{ printf "%s-dbaas-adapter-swagger" .Release.Namespace }}
spec:
  parentRefs:
  - name: {{ include "redis.gatewayApiName" . | quote }}
    namespace: {{ include "redis.gatewayApiNamespace" . | quote }}
    {{- $sectionName := dig "dbaas" "gatewayApi" "gatewaySectionName" "" .Values }}
    {{- if $sectionName }}
    sectionName: {{ $sectionName | quote }}
    {{- end }}
  hostnames:
  - {{ printf "redis-swagger.%s" .Values.CLOUD_PUBLIC_HOST | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: dbaas-redis-adapter
      port: 8080
{{- end }}
{{- end }}
